.TH "java/src/hype Directory Reference" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
java/src/hype Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcore\fP"
.br
.ti -1c
.RI "directory \fBextended\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDummyApplet\&.java\fP"
.br
.in -1c
