.TH "deprecated" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.IP "\fBMember \fBhype\&.core\&.drawable\&.HDrawable\&.boundingSize\fP ()\fP" 1c
This will be replaced with boundingBox() in the future\&.  
.IP "\fBMember \fBhype\&.core\&.drawable\&.HStage\&.autoClear\fP (boolean b)\fP" 1c
The method autoClears(boolean) should be used instead  
.IP "\fBMember \fBhype\&.core\&.util\&.H\&.autoClear\fP (boolean b)\fP" 1c
.IP "\fBMember \fBhype\&.extended\&.behavior\&.HOscillator\&.createCopy\fP ()\fP" 1c
.IP "\fBMember \fBhype\&.extended\&.colorist\&.HPixelColorist\&.getImage\fP ()\fP" 1c
.IP "\fBMember \fBhype\&.extended\&.colorist\&.HPixelColorist\&.setImage\fP (Object imgArg)\fP" 1c
.PP

