.TH "hype.extended.behavior.HTimer" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.behavior.HTimer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.behavior\&.HTrigger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHTimer\fP (int timerInterval)"
.br
.ti -1c
.RI "\fBHTimer\fP (int timerInterval, int numberOfCycles)"
.br
.ti -1c
.RI "\fBHTimer\fP \fBinterval\fP (int i)"
.br
.ti -1c
.RI "int \fBinterval\fP ()"
.br
.ti -1c
.RI "\fBHTimer\fP \fBcycleCounter\fP (int cycleIndex)"
.br
.ti -1c
.RI "int \fBcycleCounter\fP ()"
.br
.ti -1c
.RI "\fBHTimer\fP \fBnumCycles\fP (int cycles)"
.br
.ti -1c
.RI "int \fBnumCycles\fP ()"
.br
.ti -1c
.RI "\fBHTimer\fP \fBcycleIndefinitely\fP ()"
.br
.ti -1c
.RI "\fBHTimer\fP \fBuseMillis\fP ()"
.br
.ti -1c
.RI "boolean \fBusesMillis\fP ()"
.br
.ti -1c
.RI "\fBHTimer\fP \fBuseFrames\fP ()"
.br
.ti -1c
.RI "boolean \fBusesFrames\fP ()"
.br
.ti -1c
.RI "void \fBrunBehavior\fP (PApplet app)"
.br
.ti -1c
.RI "\fBHTimer\fP \fBcallback\fP (\fBHCallback\fP cb)"
.br
.ti -1c
.RI "\fBHTimer\fP \fBregister\fP ()"
.br
.ti -1c
.RI "\fBHTimer\fP \fBunregister\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
