.TH "hype.extended.layout.HGridLayout" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.layout.HGridLayout \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.layout\&.HLayout\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHGridLayout\fP (int numOfColumns)"
.br
.ti -1c
.RI "\fBHGridLayout\fP \fBcurrentIndex\fP (int i)"
.br
.ti -1c
.RI "int \fBcurrentIndex\fP ()"
.br
.ti -1c
.RI "\fBHGridLayout\fP \fBresetIndex\fP ()"
.br
.ti -1c
.RI "\fBHGridLayout\fP \fBcols\fP (int numOfColumns)"
.br
.ti -1c
.RI "int \fBcols\fP ()"
.br
.ti -1c
.RI "PVector \fBstartLoc\fP ()"
.br
.ti -1c
.RI "\fBHGridLayout\fP \fBstartLoc\fP (float x, float y)"
.br
.ti -1c
.RI "float \fBstartX\fP ()"
.br
.ti -1c
.RI "\fBHGridLayout\fP \fBstartX\fP (float x)"
.br
.ti -1c
.RI "float \fBstartY\fP ()"
.br
.ti -1c
.RI "\fBHGridLayout\fP \fBstartY\fP (float y)"
.br
.ti -1c
.RI "PVector \fBspacing\fP ()"
.br
.ti -1c
.RI "\fBHGridLayout\fP \fBspacing\fP (float xSpacing, float ySpacing)"
.br
.ti -1c
.RI "float \fBspacingX\fP ()"
.br
.ti -1c
.RI "\fBHGridLayout\fP \fBspacingX\fP (float xSpacing)"
.br
.ti -1c
.RI "float \fBspacingY\fP ()"
.br
.ti -1c
.RI "\fBHGridLayout\fP \fBspacingY\fP (float ySpacing)"
.br
.ti -1c
.RI "PVector \fBgetNextPoint\fP ()"
.br
.ti -1c
.RI "void \fBapplyTo\fP (\fBHDrawable\fP target)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
