.TH "hype.core.interfaces.HDirectable" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.interfaces.HDirectable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.interfaces\&.HLocatable\fP, and \fBhype\&.core\&.interfaces\&.HRotatable\fP\&.
.PP
Inherited by \fBhype\&.core\&.drawable\&.HDrawable\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
