.TH "hype.extended.behavior.HOscillator" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.behavior.HOscillator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.behavior\&.HBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHOscillator\fP \fBcreateCopy\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBtarget\fP (\fBHDrawable\fP d)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBtarget\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBcurrentStep\fP (float stepDegrees)"
.br
.ti -1c
.RI "float \fBcurrentStep\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBspeed\fP (float f)"
.br
.ti -1c
.RI "float \fBspeed\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBrange\fP (float minimum, float maximum)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBrange\fP (float minA, float minB, float maxA, float maxB)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBrange\fP (float minA, float minB, float minC, float maxA, float maxB, float maxC)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBmin\fP (float a)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBmin\fP (float a, float b)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBmin\fP (float a, float b, float c)"
.br
.ti -1c
.RI "float \fBmin\fP ()"
.br
.ti -1c
.RI "float \fBmin1\fP ()"
.br
.ti -1c
.RI "float \fBmin2\fP ()"
.br
.ti -1c
.RI "float \fBmin3\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBrelativeVal\fP (float a)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBrelativeVal\fP (float a, float b)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBrelativeVal\fP (float a, float b, float c)"
.br
.ti -1c
.RI "float \fBrelativeVal\fP ()"
.br
.ti -1c
.RI "float \fBrelativeVal1\fP ()"
.br
.ti -1c
.RI "float \fBrelativeVal2\fP ()"
.br
.ti -1c
.RI "float \fBrelativeVal3\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBmax\fP (float a)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBmax\fP (float a, float b)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBmax\fP (float a, float b, float c)"
.br
.ti -1c
.RI "float \fBmax\fP ()"
.br
.ti -1c
.RI "float \fBmax1\fP ()"
.br
.ti -1c
.RI "float \fBmax2\fP ()"
.br
.ti -1c
.RI "float \fBmax3\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBfreq\fP (float f)"
.br
.ti -1c
.RI "float \fBfreq\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBproperty\fP (int id)"
.br
.ti -1c
.RI "int \fBproperty\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBwaveform\fP (int waveformId)"
.br
.ti -1c
.RI "int \fBwaveform\fP ()"
.br
.ti -1c
.RI "void \fBrunBehavior\fP (PApplet app)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBregister\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBunregister\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBHOscillator\fP hype\&.extended\&.behavior\&.HOscillator\&.createCopy ()"
\fBDeprecated\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
