.TH "hype.event.HMouse" 3 "Tue May 28 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.event.HMouse \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.interfaces\&.HLocatable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHMouse\fP (PApplet app)"
.br
.ti -1c
.RI "boolean \fBstarted\fP ()"
.br
.ti -1c
.RI "boolean \fBmoved\fP ()"
.br
.ti -1c
.RI "int \fBbutton\fP ()"
.br
.ti -1c
.RI "void \fBhandleEvents\fP ()"
.br
.ti -1c
.RI "float \fBx\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHMouse\fP \fBx\fP (float newX)"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "float \fBy\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHMouse\fP \fBy\fP (float newY)"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "float \fBz\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHMouse\fP \fBz\fP (float newZ)"
.br
.RI "\fITODO\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float hype\&.event\&.HMouse\&.x ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.interfaces\&.HLocatable\fP\&.
.SS "\fBHMouse\fP hype\&.event\&.HMouse\&.x (floatnewX)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewX\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.interfaces\&.HLocatable\fP\&.
.SS "float hype\&.event\&.HMouse\&.y ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.interfaces\&.HLocatable\fP\&.
.SS "\fBHMouse\fP hype\&.event\&.HMouse\&.y (floatnewY)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewY\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.interfaces\&.HLocatable\fP\&.
.SS "float hype\&.event\&.HMouse\&.z ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.interfaces\&.HLocatable\fP\&.
.SS "\fBHMouse\fP hype\&.event\&.HMouse\&.z (floatnewZ)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewZ\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.interfaces\&.HLocatable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
