.TH "hype.core.interfaces.HLocatable" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.interfaces.HLocatable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhype\&.core\&.interfaces\&.HDirectable\fP, \fBhype\&.core\&.util\&.HMouse\fP, \fBhype\&.core\&.util\&.HVector\fP, and \fBhype\&.extended\&.util\&.HVertex\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBx\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHLocatable\fP \fBx\fP (float f)"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "float \fBy\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHLocatable\fP \fBy\fP (float f)"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "float \fBz\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHLocatable\fP \fBz\fP (float f)"
.br
.RI "\fITODO\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float hype\&.core\&.interfaces\&.HLocatable\&.x ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.core\&.drawable\&.HDrawable\fP, \fBhype\&.extended\&.util\&.HVertex\fP, \fBhype\&.core\&.util\&.HMouse\fP, and \fBhype\&.core\&.util\&.HVector\fP\&.
.SS "\fBHLocatable\fP hype\&.core\&.interfaces\&.HLocatable\&.x (floatf)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIf\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.core\&.drawable\&.HDrawable\fP, \fBhype\&.extended\&.util\&.HVertex\fP, \fBhype\&.core\&.util\&.HMouse\fP, and \fBhype\&.core\&.util\&.HVector\fP\&.
.SS "float hype\&.core\&.interfaces\&.HLocatable\&.y ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.core\&.drawable\&.HDrawable\fP, \fBhype\&.extended\&.util\&.HVertex\fP, \fBhype\&.core\&.util\&.HMouse\fP, and \fBhype\&.core\&.util\&.HVector\fP\&.
.SS "\fBHLocatable\fP hype\&.core\&.interfaces\&.HLocatable\&.y (floatf)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIf\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.core\&.drawable\&.HDrawable\fP, \fBhype\&.extended\&.util\&.HVertex\fP, \fBhype\&.core\&.util\&.HMouse\fP, and \fBhype\&.core\&.util\&.HVector\fP\&.
.SS "float hype\&.core\&.interfaces\&.HLocatable\&.z ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.core\&.drawable\&.HDrawable\fP, \fBhype\&.extended\&.util\&.HVertex\fP, \fBhype\&.core\&.util\&.HMouse\fP, and \fBhype\&.core\&.util\&.HVector\fP\&.
.SS "\fBHLocatable\fP hype\&.core\&.interfaces\&.HLocatable\&.z (floatf)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIf\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.core\&.drawable\&.HDrawable\fP, \fBhype\&.extended\&.util\&.HVertex\fP, \fBhype\&.core\&.util\&.HMouse\fP, and \fBhype\&.core\&.util\&.HVector\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
