.TH "hype.drawable.HGroup" 3 "Wed May 15 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.drawable.HGroup \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.drawable\&.HDrawable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHGroup\fP \fBcreateCopy\fP ()"
.br
.ti -1c
.RI "void \fBpaintAll\fP (PGraphics g, boolean usesZ, float currAlphaPerc)"
.br
.ti -1c
.RI "void \fBdraw\fP (PGraphics g, boolean b, float x, float y, float f)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
