.TH "hype.extended.colorist.HPixelColorist" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.colorist.HPixelColorist \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.colorist\&.HColorist\fP, and \fBhype\&.core\&.interfaces\&.HImageHolder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHPixelColorist\fP (Object imgArg)"
.br
.ti -1c
.RI "\fBHPixelColorist\fP \fBimage\fP (Object imgArg)"
.br
.ti -1c
.RI "PImage \fBimage\fP ()"
.br
.ti -1c
.RI "\fBHPixelColorist\fP \fBsetImage\fP (Object imgArg)"
.br
.ti -1c
.RI "PImage \fBgetImage\fP ()"
.br
.ti -1c
.RI "int \fBgetColor\fP (float x, float y)"
.br
.ti -1c
.RI "\fBHPixelColorist\fP \fBfillOnly\fP ()"
.br
.ti -1c
.RI "\fBHPixelColorist\fP \fBstrokeOnly\fP ()"
.br
.ti -1c
.RI "\fBHPixelColorist\fP \fBfillAndStroke\fP ()"
.br
.ti -1c
.RI "boolean \fBappliesFill\fP ()"
.br
.ti -1c
.RI "boolean \fBappliesStroke\fP ()"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBapplyColor\fP (\fBHDrawable\fP drawable)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "PImage hype\&.extended\&.colorist\&.HPixelColorist\&.getImage ()"
\fBDeprecated\fP
.RS 4
.RE
.PP

.SS "\fBHPixelColorist\fP hype\&.extended\&.colorist\&.HPixelColorist\&.setImage (ObjectimgArg)"
\fBDeprecated\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
