.TH "hype.core.behavior.HBehavior" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.behavior.HBehavior \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits HNode< HBehavior >\&.
.PP
Inherited by \fBhype\&.core\&.behavior\&.HBehaviorRegistry\&.HBehaviorSentinel\fP, \fBhype\&.core\&.behavior\&.HTrigger\fP, \fBhype\&.extended\&.behavior\&.HFollow\fP, \fBhype\&.extended\&.behavior\&.HMagneticField\fP, \fBhype\&.extended\&.behavior\&.HOscillator\fP, \fBhype\&.extended\&.behavior\&.HRotate\fP, \fBhype\&.extended\&.behavior\&.HSwarm\fP, \fBhype\&.extended\&.behavior\&.HTween\fP, and \fBhype\&.extended\&.behavior\&.HVelocity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHBehavior\fP \fBregister\fP ()"
.br
.ti -1c
.RI "\fBHBehavior\fP \fBunregister\fP ()"
.br
.ti -1c
.RI "boolean \fBpoppedOut\fP ()"
.br
.ti -1c
.RI "void \fBpopOut\fP ()"
.br
.ti -1c
.RI "void \fBswapLeft\fP ()"
.br
.ti -1c
.RI "void \fBputAfter\fP (\fBHBehavior\fP dest)"
.br
.ti -1c
.RI "void \fBputBefore\fP (\fBHBehavior\fP dest)"
.br
.ti -1c
.RI "void \fBreplaceNode\fP (\fBHBehavior\fP target)"
.br
.ti -1c
.RI "abstract void \fBrunBehavior\fP (PApplet app)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBHBehaviorRegistry\fP \fB_registry\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
