.TH "hype.drawable.HShape" 3 "Fri May 17 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.drawable.HShape \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.drawable\&.HDrawable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHShape\fP (Object shapeArg)"
.br
.ti -1c
.RI "\fBHShape\fP \fBcreateCopy\fP ()"
.br
.ti -1c
.RI "\fBHShape\fP \fBresetSize\fP ()"
.br
.ti -1c
.RI "\fBHShape\fP \fBshape\fP (Object shapeArg)"
.br
.ti -1c
.RI "PShape \fBshape\fP ()"
.br
.ti -1c
.RI "\fBHShape\fP \fBenableStyle\fP (boolean b)"
.br
.ti -1c
.RI "\fBHColorPool\fP \fBrandomColors\fP (\fBHColorPool\fP colorPool)"
.br
.ti -1c
.RI "\fBHColorPool\fP \fBrandomColors\fP (\fBHColorPool\fP colorPool, boolean isCopy)"
.br
.ti -1c
.RI "\fBHColorPool\fP \fBrandomColors\fP ()"
.br
.ti -1c
.RI "\fBHShape\fP \fBresetRandomColors\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP (PGraphics g, boolean usesZ, float drawX, float drawY, float currAlphaPerc)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
