.TH "hype.extended.behavior.HFollow" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.behavior.HFollow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.behavior\&.HBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHFollow\fP (float ease)"
.br
.ti -1c
.RI "\fBHFollow\fP (float ease, float spring)"
.br
.ti -1c
.RI "\fBHFollow\fP (float ease, float spring, \fBHLocatable\fP goal)"
.br
.ti -1c
.RI "\fBHFollow\fP \fBease\fP (float f)"
.br
.ti -1c
.RI "float \fBease\fP ()"
.br
.ti -1c
.RI "\fBHFollow\fP \fBspring\fP (float f)"
.br
.ti -1c
.RI "float \fBspring\fP ()"
.br
.ti -1c
.RI "\fBHFollow\fP \fBgoal\fP (\fBHLocatable\fP g)"
.br
.ti -1c
.RI "\fBHLocatable\fP \fBgoal\fP ()"
.br
.ti -1c
.RI "\fBHFollow\fP \fBfollowMouse\fP ()"
.br
.ti -1c
.RI "\fBHFollow\fP \fBtarget\fP (\fBHLocatable\fP f)"
.br
.ti -1c
.RI "\fBHLocatable\fP \fBtarget\fP ()"
.br
.ti -1c
.RI "void \fBrunBehavior\fP (PApplet app)"
.br
.ti -1c
.RI "\fBHFollow\fP \fBregister\fP ()"
.br
.ti -1c
.RI "\fBHFollow\fP \fBunregister\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
