.TH "hype.core.util.HColors" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.util.HColors \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.util\&.HConstants\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int[] \fBexplode\fP (int clr)"
.br
.ti -1c
.RI "static int \fBmerge\fP (int a, int r, int g, int b)"
.br
.ti -1c
.RI "static int \fBsetAlpha\fP (int clr, int newClr)"
.br
.ti -1c
.RI "static int \fBsetRed\fP (int clr, int newClr)"
.br
.ti -1c
.RI "static int \fBsetGreen\fP (int clr, int newClr)"
.br
.ti -1c
.RI "static int \fBsetBlue\fP (int clr, int newClr)"
.br
.ti -1c
.RI "static int \fBgetAlpha\fP (int clr)"
.br
.ti -1c
.RI "static int \fBgetRed\fP (int clr)"
.br
.ti -1c
.RI "static int \fBgetGreen\fP (int clr)"
.br
.ti -1c
.RI "static int \fBgetBlue\fP (int clr)"
.br
.ti -1c
.RI "static boolean \fBisTransparent\fP (int clr)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
