.TH "hype.util.HVector" 3 "Fri May 17 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.util.HVector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits PVector, and \fBhype\&.interfaces\&.HLocatable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHVector\fP (float xCoord, float yCoord)"
.br
.ti -1c
.RI "\fBHVector\fP (float xCoord, float yCoord, float zCoord)"
.br
.ti -1c
.RI "float \fBx\fP ()"
.br
.ti -1c
.RI "\fBHVector\fP \fBx\fP (float newX)"
.br
.ti -1c
.RI "float \fBy\fP ()"
.br
.ti -1c
.RI "\fBHVector\fP \fBy\fP (float newY)"
.br
.ti -1c
.RI "float \fBz\fP ()"
.br
.ti -1c
.RI "\fBHVector\fP \fBz\fP (float newZ)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
