.TH "hype.extended.behavior.HRotate" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.behavior.HRotate \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.behavior\&.HBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHRotate\fP (\fBHRotatable\fP newTarget, float dDeg)"
.br
.ti -1c
.RI "\fBHRotate\fP \fBtarget\fP (\fBHRotatable\fP r)"
.br
.ti -1c
.RI "\fBHRotatable\fP \fBtarget\fP ()"
.br
.ti -1c
.RI "\fBHRotate\fP \fBspeed\fP (float dDeg)"
.br
.ti -1c
.RI "float \fBspeed\fP ()"
.br
.ti -1c
.RI "\fBHRotate\fP \fBspeedRad\fP (float dRad)"
.br
.ti -1c
.RI "float \fBspeedRad\fP ()"
.br
.ti -1c
.RI "void \fBrunBehavior\fP (PApplet app)"
.br
.ti -1c
.RI "\fBHRotate\fP \fBregister\fP ()"
.br
.ti -1c
.RI "\fBHRotate\fP \fBunregister\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
