.TH "hype.util.HMath" 3 "Wed May 15 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.util.HMath \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.util\&.HConstants\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinit\fP (PApplet applet)"
.br
.ti -1c
.RI "static float[] \fBrotatePointArr\fP (float x, float y, float rad)"
.br
.ti -1c
.RI "static PVector \fBrotatePoint\fP (float x, float y, float rad)"
.br
.ti -1c
.RI "static float \fByAxisAngle\fP (float x1, float y1, float x2, float y2)"
.br
.ti -1c
.RI "static float \fBxAxisAngle\fP (float x1, float y1, float x2, float y2)"
.br
.ti -1c
.RI "static float[] \fBabsLocArr\fP (\fBHDrawable\fP ref, float relX, float relY)"
.br
.ti -1c
.RI "static PVector \fBabsLoc\fP (\fBHDrawable\fP ref, float relX, float relY)"
.br
.ti -1c
.RI "static PVector \fBabsLoc\fP (\fBHDrawable\fP d)"
.br
.ti -1c
.RI "static float[] \fBrelLocArr\fP (\fBHDrawable\fP ref, float absX, float absY)"
.br
.ti -1c
.RI "static PVector \fBrelLoc\fP (\fBHDrawable\fP ref, float absX, float absY)"
.br
.ti -1c
.RI "static int \fBquadrant\fP (float cx, float cy, float x, float y)"
.br
.ti -1c
.RI "static int \fBquadrant\fP (float dcx, float dcy)"
.br
.ti -1c
.RI "static float \fBellipseRadius\fP (float a, float b, float deg)"
.br
.ti -1c
.RI "static float \fBellipseRadiusRad\fP (float a, float b, float rad)"
.br
.ti -1c
.RI "static PVector \fBellipsePoint\fP (float cx, float cy, float a, float b, float deg)"
.br
.ti -1c
.RI "static PVector \fBellipsePointRad\fP (float cx, float cy, float a, float b, float rad)"
.br
.ti -1c
.RI "static float[] \fBellipsePointRadArr\fP (float cx, float cy, float a, float b, float rad)"
.br
.ti -1c
.RI "static float \fBnormalizeAngle\fP (float deg)"
.br
.ti -1c
.RI "static float \fBnormalizeAngleRad\fP (float rad)"
.br
.ti -1c
.RI "static float \fBnormalizeAngle2\fP (float deg)"
.br
.ti -1c
.RI "static float \fBnormalizeAngleRad2\fP (float rad)"
.br
.ti -1c
.RI "static float \fBsquishAngle\fP (float w, float h, float deg)"
.br
.ti -1c
.RI "static float \fBsquishAngleRad\fP (float w, float h, float rad)"
.br
.ti -1c
.RI "static float \fBlineSide\fP (float x1, float y1, float x2, float y2, float ptx, float pty)"
.br
.ti -1c
.RI "static boolean \fBcollinear\fP (float x1, float y1, float x2, float y2, float ptx, float pty)"
.br
.ti -1c
.RI "static boolean \fBleftOfLine\fP (float x1, float y1, float x2, float y2, float ptx, float pty)"
.br
.ti -1c
.RI "static boolean \fBrightOfLine\fP (float x1, float y1, float x2, float y2, float ptx, float pty)"
.br
.ti -1c
.RI "static int \fBrandomInt32\fP ()"
.br
.ti -1c
.RI "static void \fBtempSeed\fP (long seed)"
.br
.ti -1c
.RI "static void \fBremoveTempSeed\fP ()"
.br
.ti -1c
.RI "static float \fBsineWave\fP (float stepDegrees)"
.br
.ti -1c
.RI "static float \fBtriangleWave\fP (float stepDegrees)"
.br
.ti -1c
.RI "static float \fBsawWave\fP (float stepDegrees)"
.br
.ti -1c
.RI "static float \fBsquareWave\fP (float stepDegrees)"
.br
.ti -1c
.RI "static boolean \fBhasBits\fP (int target, int val)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
