.TH "hype.interfaces.HSwarmer" 3 "Wed May 15 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.interfaces.HSwarmer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.interfaces\&.HMovable\fP, and \fBhype\&.interfaces\&.HRotatable\fP\&.
.PP
Inherited by \fBhype\&.drawable\&.HDrawable\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
