.TH "hype.drawable.HText" 3 "Fri May 17 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.drawable.HText \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.drawable\&.HDrawable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHText\fP (String textString)"
.br
.ti -1c
.RI "\fBHText\fP (String textString, float size)"
.br
.ti -1c
.RI "\fBHText\fP (String textString, float size, Object fontArg)"
.br
.ti -1c
.RI "\fBHText\fP \fBcreateCopy\fP ()"
.br
.ti -1c
.RI "\fBHText\fP \fBtext\fP (String txt)"
.br
.ti -1c
.RI "String \fBtext\fP ()"
.br
.ti -1c
.RI "\fBHText\fP \fBfont\fP (Object arg)"
.br
.ti -1c
.RI "PFont \fBfont\fP ()"
.br
.ti -1c
.RI "\fBHText\fP \fBfontSize\fP (float f)"
.br
.ti -1c
.RI "float \fBfontSize\fP ()"
.br
.ti -1c
.RI "\fBHText\fP \fBwidth\fP (float w)"
.br
.ti -1c
.RI "\fBHText\fP \fBheight\fP (float h)"
.br
.ti -1c
.RI "boolean \fBcontainsRel\fP (float relX, float relY)"
.br
.ti -1c
.RI "void \fBdraw\fP (PGraphics g, boolean usesZ, float drawX, float drawY, float currAlphaPerc)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBadjustMetrics\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "PFont \fB_font\fP"
.br
.ti -1c
.RI "String \fB_text\fP"
.br
.ti -1c
.RI "float \fB_descent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
