.TH "hype.extended.util.HDrawablePool" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.util.HDrawablePool \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHDrawablePool\fP (int maximumDrawables)"
.br
.ti -1c
.RI "int \fBmax\fP ()"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBmax\fP (int m)"
.br
.ti -1c
.RI "int \fBnumActive\fP ()"
.br
.ti -1c
.RI "int \fBnumInactive\fP ()"
.br
.ti -1c
.RI "int \fBcurrentIndex\fP ()"
.br
.ti -1c
.RI "\fBHLayout\fP \fBlayout\fP ()"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBlayout\fP (\fBHLayout\fP newLayout)"
.br
.ti -1c
.RI "\fBHColorist\fP \fBcolorist\fP ()"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBcolorist\fP (\fBHColorist\fP newColorist)"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBonCreate\fP (\fBHCallback\fP callback)"
.br
.ti -1c
.RI "\fBHCallback\fP \fBonCreate\fP ()"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBonRequest\fP (\fBHCallback\fP callback)"
.br
.ti -1c
.RI "\fBHCallback\fP \fBonRequest\fP ()"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBonRelease\fP (\fBHCallback\fP callback)"
.br
.ti -1c
.RI "\fBHCallback\fP \fBonRelease\fP ()"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBautoParent\fP (\fBHDrawable\fP parent)"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBautoAddToStage\fP ()"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBautoParent\fP ()"
.br
.ti -1c
.RI "boolean \fBisFull\fP ()"
.br
.ti -1c
.RI "int \fBcount\fP ()"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBdestroy\fP ()"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBadd\fP (\fBHDrawable\fP prototype, int frequency)"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBadd\fP (\fBHDrawable\fP prototype)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBrequest\fP ()"
.br
.ti -1c
.RI "\fBHDrawablePool\fP \fBrequestAll\fP ()"
.br
.ti -1c
.RI "boolean \fBrelease\fP (\fBHDrawable\fP d)"
.br
.ti -1c
.RI "HLinkedHashSet< \fBHDrawable\fP > \fBactiveSet\fP ()"
.br
.ti -1c
.RI "HLinkedHashSet< \fBHDrawable\fP > \fBinactiveSet\fP ()"
.br
.ti -1c
.RI "HIterator< \fBHDrawable\fP > \fBiterator\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
