.TH "hype.extended.drawable.HPath" 3 "Mon Jun 3 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.drawable.HPath \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.drawable\&.HDrawable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHVertex\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHPath\fP (int pathMode)"
.br
.ti -1c
.RI "\fBHPath\fP \fBcreateCopy\fP ()"
.br
.RI "\fICreates a copy of this drawable\&. \fP"
.ti -1c
.RI "\fBHPath\fP \fBmode\fP (int m)"
.br
.ti -1c
.RI "int \fBmode\fP ()"
.br
.ti -1c
.RI "\fBHVertex\fP \fBvertex\fP (int index)"
.br
.ti -1c
.RI "\fBHPath\fP \fBremoveVertex\fP (int index)"
.br
.ti -1c
.RI "int \fBnumVertices\fP ()"
.br
.ti -1c
.RI "\fBHPath\fP \fBendPath\fP ()"
.br
.ti -1c
.RI "\fBHPath\fP \fBvertex\fP (float pxX, float pxY)"
.br
.ti -1c
.RI "\fBHPath\fP \fBvertex\fP (float handlePxX1, float handlePxY1, float handlePxX2, float handlePxY2, float pxX, float pxY)"
.br
.ti -1c
.RI "\fBHPath\fP \fBvertexPerc\fP (float percX, float percY)"
.br
.ti -1c
.RI "\fBHPath\fP \fBvertexPerc\fP (float handlePercX1, float handlePercY1, float handlePercX2, float handlePercY2, float percX, float percY)"
.br
.ti -1c
.RI "\fBHPath\fP \fBtriangle\fP (int type, int direction)"
.br
.ti -1c
.RI "\fBHPath\fP \fBpolygon\fP (int numEdges)"
.br
.ti -1c
.RI "\fBHPath\fP \fBpolygon\fP (int numEdges, float startDeg)"
.br
.ti -1c
.RI "\fBHPath\fP \fBpolygonRad\fP (int numEdges, float startRad)"
.br
.ti -1c
.RI "\fBHPath\fP \fBstar\fP (int numEdges, float depth)"
.br
.ti -1c
.RI "\fBHPath\fP \fBstar\fP (int numEdges, float depth, float startDeg)"
.br
.ti -1c
.RI "\fBHPath\fP \fBstarRad\fP (int numEdges, float depth, float startRad)"
.br
.ti -1c
.RI "\fBHPath\fP \fBclear\fP ()"
.br
.ti -1c
.RI "boolean \fBcontainsRel\fP (float relX, float relY)"
.br
.ti -1c
.RI "void \fBdraw\fP (PGraphics g, boolean usesZ, float drawX, float drawY, float currAlphaPerc)"
.br
.RI "\fIDraws this drawable\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBHPath\fP hype\&.extended\&.drawable\&.HPath\&.createCopy ()\fC [virtual]\fP"

.PP
Creates a copy of this drawable\&. This method is abstract and is meant to be implemented by the children of this class\&.
.PP
\fBReturns:\fP
.RS 4
A copy of this drawable\&. 
.RE
.PP

.PP
Implements \fBhype\&.core\&.drawable\&.HDrawable\fP\&.
.SS "void hype\&.extended\&.drawable\&.HPath\&.draw (PGraphicsg, booleanusesZ, floatdrawX, floatdrawY, floatalphaPc)\fC [virtual]\fP"

.PP
Draws this drawable\&. This method is abstract and is meant to be implemented by the children of this class\&. Also, this method is primarily called internally during the draw cycle and probably wouldn't need to be called directly\&.
.PP
\fBParameters:\fP
.RS 4
\fIg\fP The graphics context for this drawable\&. 
.br
\fIusesZ\fP Indicates if z-coordinates are used\&. 
.br
\fIdrawX\fP The x coordinate where this drawable would consider as 0 
.br
\fIdrawY\fP The y coordinate where this drawable would consider as 0 
.br
\fIalphaPc\fP The current alpha value in the draw cycle\&. 
.RE
.PP

.PP
Implements \fBhype\&.core\&.drawable\&.HDrawable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
