.TH "hype.core.util.HWarnings" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.util.HWarnings \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBwarn\fP (String type, String loc, String msg)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBNULL_TARGET\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "final String hype\&.core\&.util\&.HWarnings\&.NULL_TARGET\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
        'A target should be assigned before using this method\&.'
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
