.TH "hype.core.behavior.HBehaviorRegistry" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.behavior.HBehaviorRegistry \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHBehaviorSentinel\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBisRegistered\fP (\fBHBehavior\fP b)"
.br
.ti -1c
.RI "void \fBregister\fP (\fBHBehavior\fP b)"
.br
.ti -1c
.RI "void \fBunregister\fP (\fBHBehavior\fP b)"
.br
.ti -1c
.RI "void \fBrunAll\fP (PApplet app)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
