.TH "hype.core.layout.HLayout" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.layout.HLayout \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhype\&.extended\&.layout\&.HGridLayout\fP, and \fBhype\&.extended\&.layout\&.HShapeLayout\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBapplyTo\fP (\fBHDrawable\fP target)"
.br
.ti -1c
.RI "abstract PVector \fBgetNextPoint\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
