.TH "hype.core.behavior.HBehaviorRegistry.HBehaviorSentinel" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.behavior.HBehaviorRegistry.HBehaviorSentinel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.behavior\&.HBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHBehaviorSentinel\fP (\fBHBehaviorRegistry\fP r)"
.br
.ti -1c
.RI "void \fBrunBehavior\fP (PApplet app)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
