.TH "hype.core.util.HConstants" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.util.HConstants \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhype\&.core\&.util\&.H\fP, \fBhype\&.core\&.util\&.HColors\fP, and \fBhype\&.core\&.util\&.HMath\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBNONE\fP = 0"
.br
.ti -1c
.RI "static final int \fBLEFT\fP = 1"
.br
.ti -1c
.RI "static final int \fBRIGHT\fP = 2"
.br
.ti -1c
.RI "static final int \fBCENTER_X\fP = 3"
.br
.ti -1c
.RI "static final int \fBTOP\fP = 4"
.br
.ti -1c
.RI "static final int \fBBOTTOM\fP = 8"
.br
.ti -1c
.RI "static final int \fBCENTER_Y\fP = 12"
.br
.ti -1c
.RI "static final int \fBCENTER\fP = 15"
.br
.ti -1c
.RI "static final int \fBTOP_LEFT\fP = 5"
.br
.ti -1c
.RI "static final int \fBTOP_RIGHT\fP = 6"
.br
.ti -1c
.RI "static final int \fBBOTTOM_LEFT\fP = 9"
.br
.ti -1c
.RI "static final int \fBBOTTOM_RIGHT\fP = 10"
.br
.ti -1c
.RI "static final int \fBCENTER_LEFT\fP = 13"
.br
.ti -1c
.RI "static final int \fBCENTER_RIGHT\fP = 14"
.br
.ti -1c
.RI "static final int \fBCENTER_TOP\fP = 7"
.br
.ti -1c
.RI "static final int \fBCENTER_BOTTOM\fP = 11"
.br
.ti -1c
.RI "static final int \fBDEFAULT_BACKGROUND_COLOR\fP = 0xFFECF2F5"
.br
.ti -1c
.RI "static final int \fBCLEAR\fP = 0x00FFFFFF"
.br
.ti -1c
.RI "static final int \fBWHITE\fP = 0xFFFFFFFF"
.br
.ti -1c
.RI "static final int \fBLGREY\fP = 0xFFC0C0C0"
.br
.ti -1c
.RI "static final int \fBGREY\fP = 0xFF808080"
.br
.ti -1c
.RI "static final int \fBDGREY\fP = 0xFF404040"
.br
.ti -1c
.RI "static final int \fBBLACK\fP = 0xFF000000"
.br
.ti -1c
.RI "static final int \fBRED\fP = 0xFFFF0000"
.br
.ti -1c
.RI "static final int \fBGREEN\fP = 0xFF00FF00"
.br
.ti -1c
.RI "static final int \fBBLUE\fP = 0xFF0000FF"
.br
.ti -1c
.RI "static final int \fBCYAN\fP = 0xFF00FFFF"
.br
.ti -1c
.RI "static final int \fBMAGENTA\fP = 0xFFFF00FF"
.br
.ti -1c
.RI "static final int \fBYELLOW\fP = 0xFFFFFF00"
.br
.ti -1c
.RI "static final int \fBSAW\fP = 0"
.br
.ti -1c
.RI "static final int \fBSINE\fP = 1"
.br
.ti -1c
.RI "static final int \fBTRIANGLE\fP = 2"
.br
.ti -1c
.RI "static final int \fBSQUARE\fP = 3"
.br
.ti -1c
.RI "static final int \fBWIDTH\fP = 0"
.br
.ti -1c
.RI "static final int \fBHEIGHT\fP = 1"
.br
.ti -1c
.RI "static final int \fBSIZE\fP = 2"
.br
.ti -1c
.RI "static final int \fBALPHA\fP = 3"
.br
.ti -1c
.RI "static final int \fBX\fP = 4"
.br
.ti -1c
.RI "static final int \fBY\fP = 5"
.br
.ti -1c
.RI "static final int \fBZ\fP = 6"
.br
.ti -1c
.RI "static final int \fBLOCATION\fP = 7"
.br
.ti -1c
.RI "static final int \fBROTATION\fP = 8"
.br
.ti -1c
.RI "static final int \fBDROTATION\fP = 9"
.br
.ti -1c
.RI "static final int \fBDX\fP = 10"
.br
.ti -1c
.RI "static final int \fBDY\fP = 11"
.br
.ti -1c
.RI "static final int \fBDZ\fP = 12"
.br
.ti -1c
.RI "static final int \fBDLOC\fP = 13"
.br
.ti -1c
.RI "static final int \fBSCALE\fP = 14"
.br
.ti -1c
.RI "static final int \fBISOCELES\fP = 0"
.br
.ti -1c
.RI "static final int \fBEQUILATERAL\fP = 1"
.br
.ti -1c
.RI "static final int \fBONES\fP = 0xFFFFFFFF"
.br
.ti -1c
.RI "static final int \fBZEROES\fP = 0"
.br
.ti -1c
.RI "static final float \fBD2R\fP = PConstants\&.PI / 180f"
.br
.ti -1c
.RI "static final float \fBR2D\fP = 180f / PConstants\&.PI"
.br
.ti -1c
.RI "static final float \fBSQRT2\fP = 1\&.4142135623730951f"
.br
.ti -1c
.RI "static final float \fBPHI\fP = 1\&.618033988749895f"
.br
.ti -1c
.RI "static final float \fBPHI_1\fP = 0\&.618033988749895f"
.br
.ti -1c
.RI "static final float \fBTOLERANCE\fP = (float)10e-6"
.br
.ti -1c
.RI "static final float \fBEPSILON\fP = (float)10e-12"
.br
.ti -1c
.RI "static final \fBHCallback\fP \fBNOP\fP = new \fBHCallback\fP() {public void run(Object obj) {}}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
