.TH "hype.extended.util.HVertexNEW" 3 "Mon Jun 3 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.util.HVertexNEW \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHVertexNEW\fP (\fBHPathNEW\fP parent)"
.br
.ti -1c
.RI "\fBHPathNEW\fP \fBparent\fP ()"
.br
.ti -1c
.RI "\fBHVertexNEW\fP \fBcreateCopy\fP ()"
.br
.ti -1c
.RI "boolean \fBisCurved\fP ()"
.br
.ti -1c
.RI "boolean \fBisQuadratic\fP ()"
.br
.ti -1c
.RI "boolean \fBisCubic\fP ()"
.br
.ti -1c
.RI "\fBHVertexNEW\fP \fBset\fP (float xpx, float ypx)"
.br
.ti -1c
.RI "\fBHVertexNEW\fP \fBset\fP (float cx, float cy, float xpx, float ypx)"
.br
.ti -1c
.RI "\fBHVertexNEW\fP \fBset\fP (float cx1, float cy1, float cx2, float cy2, float xpx, float ypx)"
.br
.ti -1c
.RI "\fBHVertexNEW\fP \fBsetUV\fP (float newU, float newV)"
.br
.ti -1c
.RI "\fBHVertexNEW\fP \fBsetUV\fP (float cx1, float cy1, float xpc, float ypc)"
.br
.ti -1c
.RI "\fBHVertexNEW\fP \fBsetUV\fP (float cu1, float cv1, float cu2, float cv2, float newU, float newV)"
.br
.ti -1c
.RI "float \fBcx1\fP ()"
.br
.ti -1c
.RI "float \fBcy1\fP ()"
.br
.ti -1c
.RI "float \fBcx2\fP ()"
.br
.ti -1c
.RI "float \fBcy2\fP ()"
.br
.ti -1c
.RI "float \fBcu1\fP ()"
.br
.ti -1c
.RI "float \fBcv1\fP ()"
.br
.ti -1c
.RI "float \fBcu2\fP ()"
.br
.ti -1c
.RI "float \fBcv2\fP ()"
.br
.ti -1c
.RI "float \fBx\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHVertexNEW\fP \fBx\fP (float xpx)"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "float \fBy\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHLocatable\fP \fBy\fP (float ypx)"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "float \fBu\fP ()"
.br
.ti -1c
.RI "float \fBv\fP ()"
.br
.ti -1c
.RI "float \fBz\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHVertexNEW\fP \fBz\fP (float pxZ)"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "void \fBcomputeMinMax\fP (float[] minmax)"
.br
.ti -1c
.RI "void \fBadjust\fP (float minx, float miny, float wpc, float hpc)"
.br
.ti -1c
.RI "int \fBgetCrossings\fP (\fBHVertexNEW\fP prev, float tx, float ty)"
.br
.ti -1c
.RI "void \fBdraw\fP (PGraphics g, boolean isSimple)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float hype\&.extended\&.util\&.HVertexNEW\&.x ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "\fBHVertexNEW\fP hype\&.extended\&.util\&.HVertexNEW\&.x (floatnewX)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewX\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "float hype\&.extended\&.util\&.HVertexNEW\&.y ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "\fBHLocatable\fP hype\&.extended\&.util\&.HVertexNEW\&.y (floatnewY)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewY\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "float hype\&.extended\&.util\&.HVertexNEW\&.z ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "\fBHVertexNEW\fP hype\&.extended\&.util\&.HVertexNEW\&.z (floatnewZ)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewZ\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
