.TH "hype.extended.behavior.HVelocity" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.behavior.HVelocity \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.behavior\&.HBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHVelocity\fP \fBtarget\fP (\fBHLocatable\fP t)"
.br
.ti -1c
.RI "\fBHLocatable\fP \fBtarget\fP ()"
.br
.ti -1c
.RI "\fBHVelocity\fP \fBvelocity\fP (float velocity, float deg)"
.br
.ti -1c
.RI "\fBHVelocity\fP \fBvelocityRad\fP (float velocity, float rad)"
.br
.ti -1c
.RI "\fBHVelocity\fP \fBvelocityX\fP (float dx)"
.br
.ti -1c
.RI "float \fBvelocityX\fP ()"
.br
.ti -1c
.RI "\fBHVelocity\fP \fBvelocityY\fP (float dy)"
.br
.ti -1c
.RI "float \fBvelocityY\fP ()"
.br
.ti -1c
.RI "\fBHVelocity\fP \fBlaunchTo\fP (float goalX, float goalY, int numFrames)"
.br
.ti -1c
.RI "\fBHVelocity\fP \fBaccel\fP (float acceleration, float deg)"
.br
.ti -1c
.RI "\fBHVelocity\fP \fBaccelRad\fP (float acceleration, float rad)"
.br
.ti -1c
.RI "\fBHVelocity\fP \fBaccelX\fP (float ddx)"
.br
.ti -1c
.RI "float \fBaccelX\fP ()"
.br
.ti -1c
.RI "\fBHVelocity\fP \fBaccelY\fP (float ddy)"
.br
.ti -1c
.RI "float \fBaccelY\fP ()"
.br
.ti -1c
.RI "void \fBrunBehavior\fP (PApplet app)"
.br
.ti -1c
.RI "\fBHVelocity\fP \fBregister\fP ()"
.br
.ti -1c
.RI "\fBHVelocity\fP \fBunregister\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
