.TH "hype.core.behavior.HTrigger" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.behavior.HTrigger \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.behavior\&.HBehavior\fP\&.
.PP
Inherited by \fBhype\&.extended\&.behavior\&.HRandomTrigger\fP, and \fBhype\&.extended\&.behavior\&.HTimer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHTrigger\fP \fBcallback\fP (\fBHCallback\fP cb)"
.br
.ti -1c
.RI "\fBHCallback\fP \fBcallback\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBHCallback\fP \fB_callback\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
