.TH "hype.core.drawable.HStage" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.drawable.HStage \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.drawable\&.HDrawable\fP, and \fBhype\&.core\&.interfaces\&.HImageHolder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHStage\fP (PApplet papplet)"
.br
.ti -1c
.RI "boolean \fBinvalidChild\fP (\fBHDrawable\fP destParent)"
.br
.ti -1c
.RI "\fBHStage\fP \fBbackground\fP (int clr)"
.br
.ti -1c
.RI "\fBHStage\fP \fBbackgroundImg\fP (Object arg)"
.br
.ti -1c
.RI "\fBHStage\fP \fBimage\fP (Object imgArg)"
.br
.ti -1c
.RI "PImage \fBimage\fP ()"
.br
.ti -1c
.RI "\fBHStage\fP \fBautoClear\fP (boolean b)"
.br
.ti -1c
.RI "\fBHStage\fP \fBautoClears\fP (boolean b)"
.br
.ti -1c
.RI "boolean \fBautoClears\fP ()"
.br
.ti -1c
.RI "\fBHStage\fP \fBclear\fP ()"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBfill\fP (int clr)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBfill\fP (int clr, int \fBalpha\fP)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBfill\fP (int r, int g, int b)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBfill\fP (int r, int g, int b, int a)"
.br
.ti -1c
.RI "PVector \fBsize\fP ()"
.br
.ti -1c
.RI "float \fBwidth\fP ()"
.br
.ti -1c
.RI "float \fBheight\fP ()"
.br
.ti -1c
.RI "void \fBpaintAll\fP (PGraphics g, boolean usesZ, float currAlphaPc)"
.br
.ti -1c
.RI "void \fBdraw\fP (PGraphics g, boolean b, float \fBx\fP, float \fBy\fP, float p)"
.br
.RI "\fIDraws this drawable\&. \fP"
.ti -1c
.RI "\fBHDrawable\fP \fBcreateCopy\fP ()"
.br
.RI "\fICreates a copy of this drawable\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBHStage\fP hype\&.core\&.drawable\&.HStage\&.autoClear (booleanb)"
\fBDeprecated\fP
.RS 4
The method autoClears(boolean) should be used instead 
.RE
.PP

.SS "\fBHDrawable\fP hype\&.core\&.drawable\&.HStage\&.createCopy ()\fC [virtual]\fP"

.PP
Creates a copy of this drawable\&. This method is abstract and is meant to be implemented by the children of this class\&.
.PP
\fBReturns:\fP
.RS 4
A copy of this drawable\&. 
.RE
.PP

.PP
Implements \fBhype\&.core\&.drawable\&.HDrawable\fP\&.
.SS "void hype\&.core\&.drawable\&.HStage\&.draw (PGraphicsg, booleanusesZ, floatdrawX, floatdrawY, floatcurrAlphaPc)\fC [virtual]\fP"

.PP
Draws this drawable\&. This method is abstract and is meant to be implemented by the children of this class\&. Also, this method is primarily called internally during the draw cycle and probably wouldn't need to be called directly\&.
.PP
\fBParameters:\fP
.RS 4
\fIg\fP The graphics context for this drawable\&. 
.br
\fIusesZ\fP Indicates if z-coordinates are used\&. 
.br
\fIdrawX\fP The x coordinate where this drawable would consider as 0 
.br
\fIdrawY\fP The y coordinate where this drawable would consider as 0 
.br
\fIcurrAlphaPc\fP The current alpha value in the draw cycle\&. 
.RE
.PP

.PP
Implements \fBhype\&.core\&.drawable\&.HDrawable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
