.TH "hype.core.collection.HNode< T extends HNode< T > >" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.collection.HNode< T extends HNode< T > > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBprev\fP ()"
.br
.ti -1c
.RI "T \fBnext\fP ()"
.br
.ti -1c
.RI "boolean \fBpoppedOut\fP ()"
.br
.ti -1c
.RI "void \fBpopOut\fP ()"
.br
.ti -1c
.RI "void \fBputBefore\fP (T dest)"
.br
.ti -1c
.RI "void \fBputAfter\fP (T dest)"
.br
.ti -1c
.RI "void \fBreplaceNode\fP (T dest)"
.br
.ti -1c
.RI "void \fBswapLeft\fP ()"
.br
.ti -1c
.RI "void \fBswapRight\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "T \fB_prev\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
