.TH "hype.extended.behavior.HTween" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.behavior.HTween \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.behavior\&.HBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHTween\fP \fBtarget\fP (\fBHDrawable\fP d)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBtarget\fP ()"
.br
.ti -1c
.RI "\fBHTween\fP \fBcallback\fP (\fBHCallback\fP c)"
.br
.ti -1c
.RI "\fBHCallback\fP \fBcallback\fP ()"
.br
.ti -1c
.RI "\fBHTween\fP \fBstart\fP (float a)"
.br
.ti -1c
.RI "\fBHTween\fP \fBstart\fP (float a, float b)"
.br
.ti -1c
.RI "\fBHTween\fP \fBstart\fP (float a, float b, float c)"
.br
.ti -1c
.RI "float \fBstart\fP ()"
.br
.ti -1c
.RI "float \fBstart1\fP ()"
.br
.ti -1c
.RI "float \fBstart2\fP ()"
.br
.ti -1c
.RI "float \fBstart3\fP ()"
.br
.ti -1c
.RI "\fBHTween\fP \fBend\fP (float a)"
.br
.ti -1c
.RI "\fBHTween\fP \fBend\fP (float a, float b)"
.br
.ti -1c
.RI "\fBHTween\fP \fBend\fP (float a, float b, float c)"
.br
.ti -1c
.RI "float \fBend\fP ()"
.br
.ti -1c
.RI "float \fBend1\fP ()"
.br
.ti -1c
.RI "float \fBend2\fP ()"
.br
.ti -1c
.RI "float \fBend3\fP ()"
.br
.ti -1c
.RI "\fBHTween\fP \fBspring\fP (float f)"
.br
.ti -1c
.RI "float \fBspring\fP ()"
.br
.ti -1c
.RI "\fBHTween\fP \fBease\fP (float f)"
.br
.ti -1c
.RI "float \fBease\fP ()"
.br
.ti -1c
.RI "\fBHTween\fP \fBproperty\fP (int id)"
.br
.ti -1c
.RI "int \fBproperty\fP ()"
.br
.ti -1c
.RI "void \fBrunBehavior\fP (PApplet app)"
.br
.ti -1c
.RI "\fBHTween\fP \fBregister\fP ()"
.br
.ti -1c
.RI "\fBHTween\fP \fBunregister\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
