.TH "hype.behavior.HOscillator" 3 "Mon May 27 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.behavior.HOscillator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.behavior\&.HBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHOscillator\fP (\fBHDrawable\fP newTarget)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBcreateCopy\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBtarget\fP (\fBHDrawable\fP newTarget)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBtarget\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBcurrentStep\fP (float stepDegrees)"
.br
.ti -1c
.RI "float \fBcurrentStep\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBspeed\fP (float spd)"
.br
.ti -1c
.RI "float \fBspeed\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBrange\fP (float minimum, float maximum)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBmin\fP (float minimum)"
.br
.ti -1c
.RI "float \fBmin\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBmax\fP (float maximum)"
.br
.ti -1c
.RI "float \fBmax\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBfreq\fP (float frequency)"
.br
.ti -1c
.RI "float \fBfreq\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBrelativeVal\fP (float relativeValue)"
.br
.ti -1c
.RI "float \fBrelativeVal\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBproperty\fP (int propertyId)"
.br
.ti -1c
.RI "int \fBproperty\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBwaveform\fP (int form)"
.br
.ti -1c
.RI "int \fBwaveform\fP ()"
.br
.ti -1c
.RI "float \fBnextVal\fP ()"
.br
.ti -1c
.RI "void \fBrunBehavior\fP (PApplet app)"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBregister\fP ()"
.br
.ti -1c
.RI "\fBHOscillator\fP \fBunregister\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
