.TH "hype.core.util.HBundle" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.util.HBundle \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHBundle\fP \fBobj\fP (String key, Object value)"
.br
.ti -1c
.RI "\fBHBundle\fP \fBnum\fP (String key, float value)"
.br
.ti -1c
.RI "\fBHBundle\fP \fBbool\fP (String key, boolean value)"
.br
.ti -1c
.RI "Object \fBobj\fP (String key)"
.br
.ti -1c
.RI "String \fBstr\fP (String key)"
.br
.ti -1c
.RI "float \fBnum\fP (String key)"
.br
.ti -1c
.RI "int \fBnumI\fP (String key)"
.br
.ti -1c
.RI "boolean \fBbool\fP (String key)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
