.TH "hype.core.interfaces.HRotatable" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.interfaces.HRotatable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhype\&.core\&.interfaces\&.HDirectable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBrotationRad\fP ()"
.br
.ti -1c
.RI "\fBHRotatable\fP \fBrotationRad\fP (float rad)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
