.TH "hype.util.H" 3 "Wed May 15 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.util.H \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.util\&.HConstants\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBH\fP \fBinit\fP (PApplet applet)"
.br
.ti -1c
.RI "static \fBHStage\fP \fBstage\fP ()"
.br
.ti -1c
.RI "static PApplet \fBapp\fP ()"
.br
.ti -1c
.RI "static \fBHBehaviorRegistry\fP \fBbehaviors\fP ()"
.br
.ti -1c
.RI "static \fBHMouse\fP \fBmouse\fP ()"
.br
.ti -1c
.RI "static \fBH\fP \fBuse3D\fP (boolean b)"
.br
.ti -1c
.RI "static boolean \fBuses3D\fP ()"
.br
.ti -1c
.RI "static \fBH\fP \fBbackground\fP (int clr)"
.br
.ti -1c
.RI "static \fBH\fP \fBbackgroundImg\fP (Object arg)"
.br
.ti -1c
.RI "static \fBH\fP \fBautoClear\fP (boolean b)"
.br
.ti -1c
.RI "static boolean \fBautoClears\fP ()"
.br
.ti -1c
.RI "static \fBH\fP \fBclearStage\fP ()"
.br
.ti -1c
.RI "static \fBHDrawable\fP \fBadd\fP (\fBHDrawable\fP stageChild)"
.br
.ti -1c
.RI "static \fBHDrawable\fP \fBremove\fP (\fBHDrawable\fP stageChild)"
.br
.ti -1c
.RI "static \fBH\fP \fBdrawStage\fP ()"
.br
.ti -1c
.RI "static boolean \fBmouseStarted\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
