.TH "hype.core.interfaces.HHittable" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.interfaces.HHittable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhype\&.core\&.drawable\&.HDrawable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBcontains\fP (float absX, float absY, float absZ)"
.br
.ti -1c
.RI "boolean \fBcontains\fP (float absX, float absY)"
.br
.ti -1c
.RI "boolean \fBcontainsRel\fP (float relX, float relY, float relZ)"
.br
.ti -1c
.RI "boolean \fBcontainsRel\fP (float relX, float relY)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
