.TH "hype.core.util.H" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.util.H \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.util\&.HConstants\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBH\fP \fBinit\fP (PApplet applet)"
.br
.ti -1c
.RI "static \fBHStage\fP \fBstage\fP ()"
.br
.ti -1c
.RI "static PApplet \fBapp\fP ()"
.br
.ti -1c
.RI "static \fBHBehaviorRegistry\fP \fBbehaviors\fP ()"
.br
.ti -1c
.RI "static \fBHMouse\fP \fBmouse\fP ()"
.br
.ti -1c
.RI "static \fBH\fP \fBuse3D\fP (boolean b)"
.br
.ti -1c
.RI "static boolean \fBuses3D\fP ()"
.br
.ti -1c
.RI "static \fBH\fP \fBbackground\fP (int clr)"
.br
.ti -1c
.RI "static \fBH\fP \fBbackgroundImg\fP (Object arg)"
.br
.ti -1c
.RI "static \fBH\fP \fBautoClear\fP (boolean b)"
.br
.ti -1c
.RI "static \fBH\fP \fBautoClears\fP (boolean b)"
.br
.ti -1c
.RI "static boolean \fBautoClears\fP ()"
.br
.ti -1c
.RI "static \fBH\fP \fBclearStage\fP ()"
.br
.ti -1c
.RI "static \fBHCanvas\fP \fBadd\fP (\fBHCanvas\fP stageChild)"
.br
.ti -1c
.RI "static \fBHEllipse\fP \fBadd\fP (\fBHEllipse\fP stageChild)"
.br
.ti -1c
.RI "static \fBHGroup\fP \fBadd\fP (\fBHGroup\fP stageChild)"
.br
.ti -1c
.RI "static \fBHImage\fP \fBadd\fP (\fBHImage\fP stageChild)"
.br
.ti -1c
.RI "static \fBHPath\fP \fBadd\fP (\fBHPath\fP stageChild)"
.br
.ti -1c
.RI "static \fBHRect\fP \fBadd\fP (\fBHRect\fP stageChild)"
.br
.ti -1c
.RI "static \fBHShape\fP \fBadd\fP (\fBHShape\fP stageChild)"
.br
.ti -1c
.RI "static \fBHText\fP \fBadd\fP (\fBHText\fP stageChild)"
.br
.ti -1c
.RI "static \fBHDrawable\fP \fBadd\fP (\fBHDrawable\fP stageChild)"
.br
.ti -1c
.RI "static \fBHCanvas\fP \fBremove\fP (\fBHCanvas\fP stageChild)"
.br
.ti -1c
.RI "static \fBHEllipse\fP \fBremove\fP (\fBHEllipse\fP stageChild)"
.br
.ti -1c
.RI "static \fBHGroup\fP \fBremove\fP (\fBHGroup\fP stageChild)"
.br
.ti -1c
.RI "static \fBHImage\fP \fBremove\fP (\fBHImage\fP stageChild)"
.br
.ti -1c
.RI "static \fBHPath\fP \fBremove\fP (\fBHPath\fP stageChild)"
.br
.ti -1c
.RI "static \fBHRect\fP \fBremove\fP (\fBHRect\fP stageChild)"
.br
.ti -1c
.RI "static \fBHShape\fP \fBremove\fP (\fBHShape\fP stageChild)"
.br
.ti -1c
.RI "static \fBHText\fP \fBremove\fP (\fBHText\fP stageChild)"
.br
.ti -1c
.RI "static \fBHDrawable\fP \fBremove\fP (\fBHDrawable\fP stageChild)"
.br
.ti -1c
.RI "static \fBH\fP \fBdrawStage\fP ()"
.br
.ti -1c
.RI "static boolean \fBmouseStarted\fP ()"
.br
.ti -1c
.RI "static PImage \fBgetImage\fP (Object imgArg)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "static \fBH\fP hype\&.core\&.util\&.H\&.autoClear (booleanb)\fC [static]\fP"
\fBDeprecated\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
