.TH "hype.core.drawable.HDrawable.HDrawableIterator" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.drawable.HDrawable.HDrawableIterator \- 
.PP
An HIterator used for iterating through \fBHDrawable\fP's children\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits HIterator< HDrawable >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHDrawableIterator\fP (\fBHDrawable\fP parentDrawable)"
.br
.ti -1c
.RI "boolean \fBhasNext\fP ()"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBremove\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
An HIterator used for iterating through \fBHDrawable\fP's children\&. 

\fBAuthor:\fP
.RS 4
james 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
