.TH "hype.drawable.HStage" 3 "Tue May 21 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.drawable.HStage \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.drawable\&.HDrawable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHStage\fP (PApplet papplet)"
.br
.ti -1c
.RI "void \fBbackground\fP (int clr)"
.br
.ti -1c
.RI "void \fBbackgroundImg\fP (Object arg)"
.br
.ti -1c
.RI "\fBHStage\fP \fBautoClear\fP (boolean b)"
.br
.ti -1c
.RI "boolean \fBautoClears\fP ()"
.br
.ti -1c
.RI "\fBHStage\fP \fBclear\fP ()"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBfill\fP (int clr)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBfill\fP (int clr, int \fBalpha\fP)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBfill\fP (int r, int g, int b)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBfill\fP (int r, int g, int b, int a)"
.br
.ti -1c
.RI "PVector \fBsize\fP ()"
.br
.ti -1c
.RI "float \fBwidth\fP ()"
.br
.ti -1c
.RI "float \fBheight\fP ()"
.br
.ti -1c
.RI "void \fBpaintAll\fP (PGraphics g, boolean usesZ, float currAlphaPerc)"
.br
.ti -1c
.RI "void \fBdraw\fP (PGraphics g, boolean b, float x, float y, float p)"
.br
.RI "\fIDraws this drawable\&. \fP"
.ti -1c
.RI "void \fBcopyPropertiesFrom\fP (\fBHDrawable\fP other)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBcreateCopy\fP ()"
.br
.RI "\fICreates a copy of this drawable\&. \fP"
.ti -1c
.RI "\fBHDrawable\fP \fBloc\fP (float newX, float newY)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBx\fP (float newX)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBy\fP (float newY)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBz\fP (float newY)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBmove\fP (float dx, float dy)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBlocAt\fP (int where)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBrotation\fP (float deg)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBrotationRad\fP (float rad)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBrotate\fP (float deg)"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBrotateRad\fP (float rad)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBHDrawable\fP hype\&.drawable\&.HStage\&.createCopy ()\fC [virtual]\fP"

.PP
Creates a copy of this drawable\&. This method is abstract and is meant to be implemented by the children of this class\&.
.PP
\fBReturns:\fP
.RS 4
A copy of this drawable\&. 
.RE
.PP

.PP
Implements \fBhype\&.drawable\&.HDrawable\fP\&.
.SS "void hype\&.drawable\&.HStage\&.draw (PGraphicsg, booleanusesZ, floatdrawX, floatdrawY, floatcurrAlphaPerc)\fC [virtual]\fP"

.PP
Draws this drawable\&. This method is abstract and is meant to be implemented by the children of this class\&. Also, this method is primarily called internally during the draw cycle and probably wouldn't need to be called directly\&.
.PP
\fBParameters:\fP
.RS 4
\fIg\fP The graphics context for this drawable\&. 
.br
\fIusesZ\fP Indicates if z-coordinates are used\&. 
.br
\fIdrawX\fP The x coordinate where this drawable would consider as 0 
.br
\fIdrawY\fP The y coordinate where this drawable would consider as 0 
.br
\fIcurrAlphaPerc\fP The current alpha value in the draw cycle\&. 
.RE
.PP

.PP
Implements \fBhype\&.drawable\&.HDrawable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
