.TH "hype.core.util.HVector" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.util.HVector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHVector\fP (float xCoord, float yCoord)"
.br
.ti -1c
.RI "\fBHVector\fP (float xCoord, float yCoord, float zCoord)"
.br
.ti -1c
.RI "float \fBx\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHVector\fP \fBx\fP (float newX)"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "float \fBy\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHVector\fP \fBy\fP (float newY)"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "float \fBz\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHVector\fP \fBz\fP (float newZ)"
.br
.RI "\fITODO\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float hype\&.core\&.util\&.HVector\&.x ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "\fBHVector\fP hype\&.core\&.util\&.HVector\&.x (floatf)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIf\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "float hype\&.core\&.util\&.HVector\&.y ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "\fBHVector\fP hype\&.core\&.util\&.HVector\&.y (floatf)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIf\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "float hype\&.core\&.util\&.HVector\&.z ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.
.SS "\fBHVector\fP hype\&.core\&.util\&.HVector\&.z (floatf)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIf\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBhype\&.core\&.interfaces\&.HLocatable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
