.TH "hype.extended.behavior.HRandomTrigger" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.behavior.HRandomTrigger \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.behavior\&.HTrigger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHRandomTrigger\fP (float percChance)"
.br
.ti -1c
.RI "\fBHRandomTrigger\fP \fBchance\fP (float chancePercentage)"
.br
.ti -1c
.RI "float \fBchance\fP ()"
.br
.ti -1c
.RI "void \fBrunBehavior\fP (PApplet app)"
.br
.ti -1c
.RI "\fBHRandomTrigger\fP \fBcallback\fP (\fBHCallback\fP cb)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
