.TH "hype.extended.colorist.HColorTransform" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.extended.colorist.HColorTransform \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.colorist\&.HColorist\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHColorTransform\fP \fBoffset\fP (int off)"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBoffset\fP (int r, int g, int b, int a)"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBoffsetA\fP (int a)"
.br
.ti -1c
.RI "int \fBoffsetA\fP ()"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBoffsetR\fP (int r)"
.br
.ti -1c
.RI "int \fBoffsetR\fP ()"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBoffsetG\fP (int g)"
.br
.ti -1c
.RI "int \fBoffsetG\fP ()"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBoffsetB\fP (int b)"
.br
.ti -1c
.RI "int \fBoffsetB\fP ()"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBperc\fP (float percentage)"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBperc\fP (int r, int g, int b, int a)"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBpercA\fP (float a)"
.br
.ti -1c
.RI "float \fBpercA\fP ()"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBpercR\fP (float r)"
.br
.ti -1c
.RI "float \fBpercR\fP ()"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBpercG\fP (float g)"
.br
.ti -1c
.RI "float \fBpercG\fP ()"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBpercB\fP (float b)"
.br
.ti -1c
.RI "float \fBpercB\fP ()"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBmergeWith\fP (\fBHColorTransform\fP other)"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBcreateCopy\fP ()"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBcreateNew\fP (\fBHColorTransform\fP other)"
.br
.ti -1c
.RI "int \fBgetColor\fP (int origColor)"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBfillOnly\fP ()"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBstrokeOnly\fP ()"
.br
.ti -1c
.RI "\fBHColorTransform\fP \fBfillAndStroke\fP ()"
.br
.ti -1c
.RI "boolean \fBappliesFill\fP ()"
.br
.ti -1c
.RI "boolean \fBappliesStroke\fP ()"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBapplyColor\fP (\fBHDrawable\fP drawable)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
