.TH "hype.behavior.HMagneticField" 3 "Fri May 17 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.behavior.HMagneticField \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.behavior\&.HBehavior\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHMagnet\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHMagneticField\fP \fBaddMagnet\fP (float sx, float sy, float nx, float ny)"
.br
.ti -1c
.RI "\fBHMagnet\fP \fBmagnet\fP (int index)"
.br
.ti -1c
.RI "\fBHMagneticField\fP \fBremoveMagnet\fP (int index)"
.br
.ti -1c
.RI "\fBHMagneticField\fP \fBaddTarget\fP (\fBHDrawable\fP d)"
.br
.ti -1c
.RI "\fBHMagneticField\fP \fBremoveTarget\fP (\fBHDrawable\fP d)"
.br
.ti -1c
.RI "float \fBgetRotation\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBrunBehavior\fP (PApplet app)"
.br
.ti -1c
.RI "\fBHMagneticField\fP \fBregister\fP ()"
.br
.ti -1c
.RI "\fBHMagneticField\fP \fBunregister\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
