.TH "hype.core.collection.HLinkedList< T >" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.collection.HLinkedList< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhype\&.core\&.collection\&.HLinkedHashSet< T >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHLinkedListIterator< U >\fP"
.br
.ti -1c
.RI "class \fBHLinkedListNode< U >\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBfirst\fP ()"
.br
.ti -1c
.RI "T \fBlast\fP ()"
.br
.ti -1c
.RI "T \fBget\fP (int index)"
.br
.ti -1c
.RI "boolean \fBpush\fP (T content)"
.br
.ti -1c
.RI "boolean \fBadd\fP (T content)"
.br
.ti -1c
.RI "boolean \fBinsert\fP (T content, int index)"
.br
.ti -1c
.RI "T \fBpop\fP ()"
.br
.ti -1c
.RI "T \fBpull\fP ()"
.br
.ti -1c
.RI "T \fBremoveAt\fP (int index)"
.br
.ti -1c
.RI "void \fBremoveAll\fP ()"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "boolean \fBinRange\fP (int index)"
.br
.ti -1c
.RI "HLinkedListIterator< T > \fBiterator\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "HLinkedListNode< T > \fBnodeAt\fP (int i)"
.br
.ti -1c
.RI "HLinkedListNode< T > \fBregister\fP (T obj)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "HLinkedListNode< T > \fB_firstSentinel\fP"
.br
.ti -1c
.RI "int \fB_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
