.TH "hype.core.collection.HLinkedHashSet< T >" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.collection.HLinkedHashSet< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhype\&.core\&.collection\&.HLinkedList< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBremove\fP (T content)"
.br
.ti -1c
.RI "boolean \fBadd\fP (T content)"
.br
.ti -1c
.RI "boolean \fBpush\fP (T content)"
.br
.ti -1c
.RI "boolean \fBinsert\fP (T content, int index)"
.br
.ti -1c
.RI "T \fBpull\fP ()"
.br
.ti -1c
.RI "T \fBpop\fP ()"
.br
.ti -1c
.RI "T \fBremoveAt\fP (int index)"
.br
.ti -1c
.RI "void \fBremoveAll\fP ()"
.br
.ti -1c
.RI "boolean \fBcontains\fP (T obj)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "HLinkedListNode< T > \fBregister\fP (T obj)"
.br
.ti -1c
.RI "T \fBunregister\fP (T obj)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
