.TH "hype.core.collection.HLinkedList< T >.HLinkedListNode< U >" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.collection.HLinkedList< T >.HLinkedListNode< U > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits HNode< HLinkedListNode< U > >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHLinkedListNode\fP (U nodeContent)"
.br
.ti -1c
.RI "U \fBcontent\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
