.TH "hype.core.colorist.HColorist" 3 "Wed Jun 19 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.core.colorist.HColorist \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhype\&.extended\&.colorist\&.HColorField\fP, \fBhype\&.extended\&.colorist\&.HColorPool\fP, \fBhype\&.extended\&.colorist\&.HColorTransform\fP, and \fBhype\&.extended\&.colorist\&.HPixelColorist\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHColorist\fP \fBfillOnly\fP ()"
.br
.ti -1c
.RI "\fBHColorist\fP \fBstrokeOnly\fP ()"
.br
.ti -1c
.RI "\fBHColorist\fP \fBfillAndStroke\fP ()"
.br
.ti -1c
.RI "boolean \fBappliesFill\fP ()"
.br
.ti -1c
.RI "boolean \fBappliesStroke\fP ()"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBapplyColor\fP (\fBHDrawable\fP drawable)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
