.TH "hype.util.HColorUtil" 3 "Fri May 17 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.util.HColorUtil \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int[] \fBexplode\fP (int clr)"
.br
.ti -1c
.RI "static int \fBmerge\fP (int a, int r, int g, int b)"
.br
.ti -1c
.RI "static int \fBsetAlpha\fP (int clr, int newAlpha)"
.br
.ti -1c
.RI "static int \fBsetRed\fP (int clr, int newRed)"
.br
.ti -1c
.RI "static int \fBsetGreen\fP (int clr, int newGreen)"
.br
.ti -1c
.RI "static int \fBsetBlue\fP (int clr, int newBlue)"
.br
.ti -1c
.RI "static int \fBgetAlpha\fP (int clr)"
.br
.ti -1c
.RI "static int \fBgetRed\fP (int clr)"
.br
.ti -1c
.RI "static int \fBgetGreen\fP (int clr)"
.br
.ti -1c
.RI "static int \fBgetBlue\fP (int clr)"
.br
.ti -1c
.RI "static int \fBmultiply\fP (int c1, int c2)"
.br
.ti -1c
.RI "static int \fBmultiplyAlpha\fP (int clr, int a)"
.br
.ti -1c
.RI "static int \fBmultiplyRed\fP (int clr, int r)"
.br
.ti -1c
.RI "static int \fBmultiplyGreen\fP (int clr, int g)"
.br
.ti -1c
.RI "static int \fBmultiplyBlue\fP (int clr, int b)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
