.TH "hype.interfaces.HLocatable" 3 "Tue May 28 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.interfaces.HLocatable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhype\&.event\&.HMouse\fP, \fBhype\&.interfaces\&.HSwarmer\fP, and \fBhype\&.util\&.HVector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBx\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHLocatable\fP \fBx\fP (float newX)"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "float \fBy\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHLocatable\fP \fBy\fP (float newY)"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "float \fBz\fP ()"
.br
.RI "\fITODO\&. \fP"
.ti -1c
.RI "\fBHLocatable\fP \fBz\fP (float newZ)"
.br
.RI "\fITODO\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float hype\&.interfaces\&.HLocatable\&.x ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.drawable\&.HDrawable\fP, \fBhype\&.event\&.HMouse\fP, and \fBhype\&.util\&.HVector\fP\&.
.SS "\fBHLocatable\fP hype\&.interfaces\&.HLocatable\&.x (floatnewX)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewX\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.drawable\&.HDrawable\fP, \fBhype\&.drawable\&.HStage\fP, \fBhype\&.event\&.HMouse\fP, and \fBhype\&.util\&.HVector\fP\&.
.SS "float hype\&.interfaces\&.HLocatable\&.y ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.drawable\&.HDrawable\fP, \fBhype\&.event\&.HMouse\fP, and \fBhype\&.util\&.HVector\fP\&.
.SS "\fBHLocatable\fP hype\&.interfaces\&.HLocatable\&.y (floatnewY)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewY\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.drawable\&.HDrawable\fP, \fBhype\&.drawable\&.HStage\fP, \fBhype\&.event\&.HMouse\fP, and \fBhype\&.util\&.HVector\fP\&.
.SS "float hype\&.interfaces\&.HLocatable\&.z ()"

.PP
TODO\&. \fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.drawable\&.HDrawable\fP, \fBhype\&.event\&.HMouse\fP, and \fBhype\&.util\&.HVector\fP\&.
.SS "\fBHLocatable\fP hype\&.interfaces\&.HLocatable\&.z (floatnewZ)"

.PP
TODO\&. This method returns \fCthis\fP so it could be chained with other methods of this class\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewZ\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBhype\&.drawable\&.HDrawable\fP, \fBhype\&.drawable\&.HStage\fP, \fBhype\&.event\&.HMouse\fP, and \fBhype\&.util\&.HVector\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
