.TH "hype.drawable.HDrawable.HDrawableIterator" 3 "Fri May 17 2013" "HYPE_processing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hype.drawable.HDrawable.HDrawableIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits HIterator< HDrawable >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHDrawableIterator\fP (\fBHDrawable\fP parentDrawable)"
.br
.ti -1c
.RI "boolean \fBhasNext\fP ()"
.br
.ti -1c
.RI "\fBHDrawable\fP \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBremove\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for HYPE_processing from the source code\&.
