public static interface HConstants {
	public static final int
		NONE = 0,
		SIN = 1,
		COS = 2,
		TAN = 3,
		LEFT   = 1, 
		RIGHT  = 2, 
		TOP    = 4, 
		BOTTOM = 8, 
		CENTER_X = 3, 
		CENTER_Y = 12, 
		CENTER = 15, 
		DEFAULT_BACKGROUND_COLOR = 0xFFECF2F5,
		DEFAULT_FILL = 0x00FFFFFF,
		DEFAULT_STROKE = 0x00FFFFFF,
		SAW = 0,
		SINE = 1,
		TRIANGLE = 2,
		SQUARE = 3,
		WIDTH = 0,
		HEIGHT = 1,
		SIZE = 2,
		ALPHA = 3,
		X = 4,
		Y = 5,
		LOCATION = 6,
		ROTATION = 7,
		DROTATION = 8,
		DX = 9,
		DY = 10,
		DLOC = 11,
		SCALE = 12,
		ISOCELES = 0,
		EQUILATERAL = 1;
	public static final float
		D2R = PConstants.PI / 180f,
		R2D = 180f / PConstants.PI;
}
