/* autogenerated by Processing revision 1293 on 2023-08-05 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import hype.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class HPath_002_star extends PApplet {



public void setup() {
	/* size commented out by preprocessor */;
	H.init(this).background(0xFF242424);

	HPath star1 = new HPath();
	star1
		.star( 5, 0.75f ) // numEdges, depth
		.size(150,150)
		.strokeWeight(6)
		.stroke(0xFF000000, 100)
		.fill(0xFFFF9900)
		.loc(50, 50)
	;
	H.add(star1);

	HPath star2 = new HPath();
	star2
		.star( 5, 0.5f ) // numEdges, depth
		.size(150,150)
		.strokeWeight(6)
		.stroke(0xFF000000, 100)
		.fill(0xFFFF6600)
		.loc(245, 50)
	;
	H.add(star2);

	HPath star3 = new HPath();
	star3
		.star( 5, 0.25f ) // numEdges, depth
		.size(150,150)
		.strokeWeight(6)
		.stroke(0xFF000000, 100)
		.fill(0xFFFF3300)
		.loc(440, 50)
	;
	H.add(star3);


	HPath star4 = new HPath();
	star4.star( 7, 0.75f ).size(150,150).strokeWeight(6).stroke(0xFF000000, 100).fill(0xFFFF9900).loc(50, 245);
	H.add(star4);

	HPath star5 = new HPath();
	star5.star( 7, 0.5f ).size(150,150).strokeWeight(6).stroke(0xFF000000, 100).fill(0xFFFF6600).loc(245, 245);
	H.add(star5);

	HPath star6 = new HPath();
	star6.star( 7, 0.25f ).size(150,150).strokeWeight(6).stroke(0xFF000000, 100).fill(0xFFFF3300).loc(440, 245);
	H.add(star6);


	HPath star7 = new HPath();
	star7.star( 9, 0.75f ).size(150,150).strokeWeight(6).stroke(0xFF000000, 100).fill(0xFFFF9900).loc(50, 440);
	H.add(star7);

	HPath star8 = new HPath();
	star8.star( 9, 0.5f ).size(150,150).strokeWeight(6).stroke(0xFF000000, 100).fill(0xFFFF6600).loc(245, 440);
	H.add(star8);

	HPath star9 = new HPath();
	star9.star( 9, 0.25f ).size(150,150).strokeWeight(6).stroke(0xFF000000, 100).fill(0xFFFF3300).loc(440, 440);
	H.add(star9);

	H.drawStage();
	noLoop();
}

public void draw() {

}


  public void settings() { size(640, 640); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "HPath_002_star" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
