/* autogenerated by Processing revision 1293 on 2023-08-05 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import hype.*;
import hype.extended.colorist.HPixelColorist;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class HSprite_004 extends PApplet {




HImage         clrSRC;
HPixelColorist clrHPC;
HRect          clrMarker;
int            clrMin = 0;
int            clrMax = 200;
int[]        clr;

HSprite        s1, s2, s3, s4, s5, s6, s7, s8, s9;

public void setup() {
	/* size commented out by preprocessor */;
	H.init(this).background(0xFFFF3300).use3D(true);

	H.add( clrSRC = new HImage("color.png") );
	clrHPC = new HPixelColorist(clrSRC);
	H.add(clrMarker = new HRect(2,10)).noStroke().fill(0xFFCCCCCC).loc(0,15);

	clr = new int[ clrMax ];
	for (int i = 0; i < clrMax; i++) {
		float tempPos = (clrSRC.width() / clrMax) * i;
		clr[i] = clrHPC.getColor(tempPos,0);
	}

	H.add(s1 = new HSprite(180,180).texture(new HImage("tex1.png"))).loc((width/2)-190, (height/2)-190).anchorAt(H.CENTER);
	H.add(s2 = new HSprite(180,180).texture(new HImage("tex2.png"))).loc((width/2), (height/2)-190).anchorAt(H.CENTER);
	H.add(s3 = new HSprite(180,180).texture(new HImage("tex3.png"))).loc((width/2)+190, (height/2)-190).anchorAt(H.CENTER);

	H.add(s4 = new HSprite(180,180).texture(new HImage("tex1.jpg"))).loc((width/2)-190, (height/2)).anchorAt(H.CENTER);
	H.add(s5 = new HSprite(180,180).texture(new HImage("tex2.jpg"))).loc((width/2), (height/2)).anchorAt(H.CENTER);
	H.add(s6 = new HSprite(180,180).texture(new HImage("tex3.jpg"))).loc((width/2)+190, (height/2)).anchorAt(H.CENTER);

	H.add(s7 = new HSprite(180,180).texture(new HImage("img1.jpg"))).loc((width/2)-190, (height/2)+190).anchorAt(H.CENTER);
	H.add(s8 = new HSprite(180,180).texture(new HImage("img2.jpg"))).loc((width/2), (height/2)+190).anchorAt(H.CENTER);
	H.add(s9 = new HSprite(180,180).texture(new HImage("img3.jpg"))).loc((width/2)+190, (height/2)+190).anchorAt(H.CENTER);
}

public void draw() {
	H.drawStage();

	s1.fill( clr[clrMin] );
	s2.fill( clr[clrMin] );
	s3.fill( clr[clrMin] );
	s4.fill( clr[clrMin] );
	s5.fill( clr[clrMin] );
	s6.fill( clr[clrMin] );
	s7.fill( clr[clrMin] );
	s8.fill( clr[clrMin] );
	s9.fill( clr[clrMin] );

	// update color position

	clrMin = ++clrMin%clrMax;
	float tempPos = ((clrSRC.width() / clrMax) * clrMin);
	clrMarker.loc(tempPos,15);
}


  public void settings() { size(640, 640, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "HSprite_004" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
